//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_data
    {
        public string cdsc_ug { get; set; }
        public string ctipo_doc { get; set; }
        public string cruc { get; set; }
        public string ccod_ficha { get; set; }
        public string dfec_ins_reg { get; set; }
        public string dfch_crea { get; set; }
        public string cnro_doc { get; set; }
        public string cpaterno { get; set; }
        public string cmaterno { get; set; }
        public string cnombres { get; set; }
        public string cdireccion { get; set; }
        public string ccelular { get; set; }
        public string cemail { get; set; }
        public string ccod_ccosto { get; set; }
        public string cdsc_ccosto { get; set; }
        public string ccod_art { get; set; }
        public string cdsc_art { get; set; }
        public string cdsc_pago { get; set; }
        public string cdoc { get; set; }
        public string cdoc_serie { get; set; }
        public string cdoc_nro { get; set; }
        public string curl { get; set; }
        public Nullable<decimal> ntotal { get; set; }
        public Nullable<int> nletras { get; set; }
        public string cstatus_ficha { get; set; }
        public string ctipo { get; set; }
        public Nullable<decimal> id_lnfact { get; set; }
        public Nullable<int> idpostulacion { get; set; }
        public string cdsc_convocatoria { get; set; }
        public string cdsc_carrera { get; set; }
        public string cdsc_modalidad { get; set; }
        public string coamra { get; set; }
        public string cdsc_mon { get; set; }
        public string cdist_nota_postula { get; set; }
        public string cfecha_nacimiento { get; set; }
        public string csexo { get; set; }
        public string cecivil { get; set; }
        public string gcod_convocatoria { get; set; }
        public string cdsc_descripcion { get; set; }
    }
}
